"""Report generation from raw samples (design §12.5).

Every number in the report is read from a raw sample file written by the runner.
The generator never computes a measurement of its own, so a number cannot appear
in the report without a file behind it, and the report says which file.

The report also states its own limits. Absolute scores on generated pages do not
transfer to real documents, and a benchmark is valid only for the host and date
in its manifest. Both are printed, not implied.
"""

from __future__ import annotations

import json
import statistics
from dataclasses import asdict, dataclass, field
from pathlib import Path

from forgesight.bench.protocol import (
    PROTOCOL_VERSION,
    TrialResult,
    aggregate,
    judge_stability,
    speedup_statement,
    summarize_env,
)
from forgesight.settings import REPO_ROOT


def _rel_to_repo(path: str) -> str:
    """Repo-relative where possible, bare filename otherwise.

    Reports are committed and read on machines that are not this one, so an
    absolute path is both unusable there and a leak of the author's home
    directory into a public repository. Falls back to the filename rather than
    failing, because a raw-sample listing is a provenance aid and must never be
    the reason a report fails to generate.
    """
    try:
        return str(Path(path).resolve().relative_to(REPO_ROOT))
    except (ValueError, OSError):
        return Path(path).name


DISCLAIMERS = [
    "All pages in this report were generated by this repository and are labelled "
    "SYNTHETIC. They are not real documents.",
    "The synthetic box conventions do not match DocLayNet's, so the absolute mAP "
    "figures here are NOT comparable with published numbers. Only relative "
    "comparisons between candidates on the same dataset are meaningful.",
    "Every measurement below is valid only for the host, OS and library versions "
    "in the environment manifest, and only for the date it was taken.",
    "A candidate that happens to suit the synthetic convention better can score "
    "well here and worse on real pages. That caveat applies to every comparison.",
]


@dataclass(slots=True)
class ReportInput:
    env: dict
    quality: list[dict] = field(default_factory=list)
    trials: list[TrialResult] = field(default_factory=list)
    raw_files: list[str] = field(default_factory=list)
    dataset_hashes: list[dict] = field(default_factory=list)
    gating: list[dict] = field(default_factory=list)
    memory_model: dict = field(default_factory=dict)
    refusals: list[str] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)


def _fmt(v, unit: str = "", nd: int = 2) -> str:
    if v is None:
        return "n/a"
    if isinstance(v, float):
        return f"{v:,.{nd}f}{unit}"
    return f"{v:,}{unit}" if isinstance(v, int) else f"{v}{unit}"


def _table(headers: list[str], rows: list[list[str]]) -> str:
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join(["---"] * len(headers)) + "|"]
    out.extend("| " + " | ".join(r) + " |" for r in rows)
    return "\n".join(out)


def build(data: ReportInput) -> str:
    env = data.env
    stamp = summarize_env(env)
    by_config: dict[str, list[TrialResult]] = {}
    for t in data.trials:
        by_config.setdefault(t.config_key, []).append(t)
    aggs = {k: {**aggregate(v), "env": env} for k, v in by_config.items()}

    lines: list[str] = []
    add = lines.append

    add("# ForgeSight benchmark report")
    add("")
    add(f"- protocol version: `{PROTOCOL_VERSION}`")
    add(f"- measured: {env.get('captured_at', 'unknown')}")
    add(f"- host: {stamp}")
    add(f"- git sha: `{env.get('git_sha', 'unknown')}`")
    add(f"- power source during capture: {env.get('power_source', 'unknown')}"
        f"{' (Low Power Mode ON)' if env.get('low_power_mode') else ''}")
    add(f"- free memory before/after: {env.get('memory_pressure_before', '?')} / "
        f"{env.get('memory_pressure_after', '?')}")
    add("")

    if data.refusals:
        add("## Conditions that would normally block measurement")
        add("")
        for r in data.refusals:
            add(f"- {r}")
        add("")
        add("> These numbers were taken under conditions the protocol would refuse "
            "by default. They are reported with the caveat rather than discarded, "
            "and should not be compared with a run taken under nominal conditions.")
        add("")

    add("## Limits")
    add("")
    for d in DISCLAIMERS:
        add(f"- {d}")
    add("")

    if data.dataset_hashes:
        add("## Datasets")
        add("")
        # Grouped by name and version. Several manifest hashes under one version
        # is the honest signal that truncated or differently seeded builds were
        # mixed in, so it is shown rather than collapsed away.
        grouped: dict[tuple[str, str], set[str]] = {}
        synthetic: dict[tuple[str, str], bool] = {}
        for d in data.dataset_hashes:
            key = (d.get("name", "?"), d.get("semver", "?"))
            grouped.setdefault(key, set()).add((d.get("manifest_hash") or "")[:16])
            synthetic[key] = bool(d.get("synthetic", True))
        add(_table(
            ["dataset", "version", "manifest hash(es)", "synthetic"],
            [[k[0], k[1], ", ".join(f"`{h}`" for h in sorted(v)),
              "yes" if synthetic[k] else "no"]
             for k, v in sorted(grouped.items())],
        ))
        if any(len(v) > 1 for v in grouped.values()):
            add("")
            add("> More than one manifest hash under a single version means builds "
                "with different content or different page counts were both loaded. "
                "Each is a distinct dataset; they are not interchangeable.")
        add("")

    if data.quality:
        add("## Quality")
        add("")
        add(_table(
            ["candidate", "dataset", "mAP@[.5:.95]", "mAP@.50", "detections", "images"],
            [[q.get("candidate", "?"), q.get("dataset", "?"),
              _fmt(q.get("map"), nd=5), _fmt(q.get("map50"), nd=5),
              _fmt(q.get("n_detections")), _fmt(q.get("n_images"))]
             for q in data.quality],
        ))
        add("")

    if data.gating:
        add("## Release gates")
        add("")
        add(_table(
            ["candidate", "gate", "passed", "observed", "threshold"],
            [[g.get("candidate", "?"), g.get("gate", "?"),
              "yes" if g.get("passed") else "**no**",
              _fmt(g.get("observed"), nd=5), _fmt(g.get("threshold"), nd=5)]
             for g in data.gating],
        ))
        add("")

    if aggs:
        add("## Throughput and latency")
        add("")
        add("Queue-inclusive latency includes the wait for a worker; service time "
            "does not. Both are reported because a single unnamed latency number "
            "is how a benchmark misleads.")
        add("")
        rows = []
        for key in sorted(aggs):
            a = aggs[key]
            st = a.get("stability", {})
            rows.append([
                f"`{key}`",
                _fmt(a.get("throughput_pages_per_s", {}).get("median_of_medians"), nd=3),
                f"{_fmt(a.get('throughput_pages_per_s', {}).get('min'), nd=3)}"
                f"–{_fmt(a.get('throughput_pages_per_s', {}).get('max'), nd=3)}",
                _fmt(a.get("queue_inclusive_p95_ms", {}).get("median_of_medians")),
                str(a.get("queue_inclusive_p95_ms", {}).get("ci95")),
                _fmt(a.get("service_p50_ms")),
                _fmt(round((a.get("peak_rss_bytes") or 0) / 1e6, 1), " MB"),
                "stable" if st.get("stable") else "**unstable**",
            ])
        add(_table(
            ["configuration", "pages/s (median)", "pages/s range",
             "queue-incl. p95 (ms)", "p95 95% CI", "service p50 (ms)",
             "peak RSS", "stability"],
            rows,
        ))
        add("")

        unstable = [k for k, a in aggs.items() if not a.get("stability", {}).get("stable")]
        if unstable:
            add("### Excluded from comparison")
            add("")
            for key in unstable:
                reasons = aggs[key].get("stability", {}).get("reasons", [])
                add(f"- `{key}`: " + "; ".join(reasons))
            add("")

        stable_keys = [k for k in sorted(aggs)
                       if aggs[k].get("stability", {}).get("stable")]
        if len(stable_keys) >= 2:
            add("### Comparisons")
            add("")
            best = max(stable_keys, key=lambda k: aggs[k]["throughput_pages_per_s"][
                "median_of_medians"])
            for other in stable_keys:
                if other == best:
                    continue
                add(f"- {speedup_statement(aggs[best], aggs[other], best, other)}")
            add("")

    if data.memory_model and "error" not in data.memory_model:
        add("## Memory model and admission")
        add("")
        m = data.memory_model
        marginal = m.get("marginal_peak_above_baseline") or {}
        add(_table(
            ["quantity", "value"],
            [
                ["steady state M0",
                 _fmt(round((m.get("m0_bytes") or 0) / 1e6, 1), " MB")],
                ["marginal cost per 640x640 item (m_item)",
                 _fmt(round((m.get("m_item_bytes") or 0) / 1e6, 2), " MB")],
                ["max fit residual",
                 _fmt(round((m.get("max_residual") or 0) / 1e6, 2), " MB")],
                ["fit usable for admission",
                 "yes" if m.get("calibration_valid", True) else "**no**"],
                ["admission mispredictions", _fmt(m.get("mispredictions"))],
                ["observations", _fmt(m.get("n_observations"))],
            ],
        ))
        add("")
        if m.get("calibration_note"):
            add(f"> **The linear memory model did not reproduce on this host.** "
                f"{m['calibration_note']} This is a result, not a defect in the "
                f"measurement: it means admission on this host is driven by measured "
                f"peaks rather than by a fitted line, and that a controller trusting "
                f"the fit would be operating on fiction.")
            add("")
        if marginal:
            add("Marginal peak above the post-warm baseline, per batch size:")
            add("")
            add(_table(
                ["batch size", "marginal peak", "high-water including baseline"],
                [[f"b={k}",
                  _fmt(round(v / 1e6, 2), " MB"),
                  _fmt(round((m.get("high_water_including_baseline", {}).get(k, 0))
                             / 1e6, 1), " MB")]
                 for k, v in sorted(marginal.items(), key=lambda kv: int(kv[0]))],
            ))
            add("")
        if m.get("method"):
            add(f"Method: {m['method']}.")
            add("")
        add("Admission predicts peak RSS as `M0 + b * m_item` and picks the "
            "largest batch that fits the budget. The prediction is checked against "
            "the measured marginal peak on every batch; the misprediction count "
            "above is that check, reported rather than assumed correct.")
        add("")
        # Design §15 phase 4 exit criterion. Regenerated with every run rather
        # than maintained by hand, so the figure cannot drift from the numbers
        # above it. Name is stable across runs so the markdown reference stays
        # valid and the file shows as a content diff, not add/delete churn.
        if marginal:
            fig = data.memory_model.get("plot_file")
            if fig:
                add(f"![Admission: predicted vs observed peak RSS]({fig})")
                add("")

    if data.raw_files:
        add("## Raw samples")
        add("")
        add("Every number above is read from one of these files. Nothing in this "
            "report is computed independently of them.")
        add("")
        for f in sorted(data.raw_files):
            add(f"- `{_rel_to_repo(f)}`")
        add("")

    if data.notes:
        add("## Notes")
        add("")
        for n in data.notes:
            add(f"- {n}")
        add("")

    return "\n".join(lines) + "\n"


def write_plot(data: ReportInput, path: Path) -> Path | None:
    """Write the admission predicted-vs-observed figure. None if there is nothing to draw.

    Called before `write`, so the markdown can reference the file by name. The
    name is fixed rather than date-stamped: these reports are tracked in git
    alongside the evidence they cite, and a date in the filename would turn
    every regeneration into a rename.
    """
    m = data.memory_model or {}
    samples = m.get("samples") or {}
    if not samples:
        return None
    from forgesight.bench.plot import Series, predicted_vs_observed_svg

    svg = predicted_vs_observed_svg([
        Series(
            label="egret-medium / onnxruntime",
            samples={int(k): float(v) for k, v in samples.items()},
            m0=float(m.get("m0_bytes") or 0.0),
            m_item=float(m.get("m_item_bytes") or 0.0),
            valid=bool(m.get("calibration_valid", m.get("valid", True))),
        )
    ])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(svg)
    data.memory_model["plot_file"] = path.name
    return path


def write(data: ReportInput, path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(build(data))
    return path


def summary_json(data: ReportInput) -> dict:
    by_config: dict[str, list[TrialResult]] = {}
    for t in data.trials:
        by_config.setdefault(t.config_key, []).append(t)
    return {
        "protocol_version": PROTOCOL_VERSION,
        "env": data.env,
        "host_stamp": summarize_env(data.env),
        "quality": data.quality,
        "gates": data.gating,
        "datasets": data.dataset_hashes,
        "throughput": {k: aggregate(v) for k, v in by_config.items()},
        "stability": {k: asdict(judge_stability(v)) for k, v in by_config.items()},
        "memory_model": data.memory_model,
        "raw_files": [_rel_to_repo(f) for f in data.raw_files],
        "refusals": data.refusals,
        "disclaimers": DISCLAIMERS,
    }


def median_of(values: list[float]) -> float:
    return statistics.median(values) if values else float("nan")


def write_json(data: ReportInput, path: Path) -> Path:
    """The machine-readable twin of the report, from the same inputs."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(summary_json(data), indent=2, sort_keys=True) + "\n")
    return path


__all__ = [
    "DISCLAIMERS",
    "ReportInput",
    "build",
    "median_of",
    "summary_json",
    "write",
    "write_json",
]
