"""FastAPI application factory (design §7).

The API process runs no inference. That is the point of the split: a request
handler that loaded a model would make per-runtime memory unmeasurable and
would let one slow upload block the event loop behind a forward pass.
"""

from __future__ import annotations

import logging
from contextlib import asynccontextmanager

from fastapi import FastAPI, Request
from fastapi.responses import FileResponse, JSONResponse

from forgesight.api import routes_batches, routes_releases, routes_reports, routes_sessions
from forgesight.api.deps import get_pool_singleton
from forgesight.db.migrate import migrate
from forgesight.settings import REPO_ROOT, get_settings

log = logging.getLogger("forgesight.api")


@asynccontextmanager
async def lifespan(app: FastAPI):
    s = get_settings()
    s.ensure_dirs()
    pool = get_pool_singleton()
    applied = migrate(pool, verbose=False)
    if applied:
        log.info("applied migrations: %s", ", ".join(applied))
    yield


def create_app() -> FastAPI:
    s = get_settings()
    logging.basicConfig(level=s.log_level)

    app = FastAPI(
        title="ForgeSight",
        version="0.2.0",
        summary="Document-layout inference workbench",
        description=(
            "Upload page images or PDFs, run them on the active release, shadow-compare "
            "a candidate, check release gates, and promote or roll back. All results are "
            "measured on a labelled host; nothing here is transferred from a model card."
        ),
        lifespan=lifespan,
    )

    app.include_router(routes_sessions.router)
    app.include_router(routes_batches.router)
    app.include_router(routes_releases.router)
    app.include_router(routes_reports.router)

    _mount_web(app)

    @app.get("/healthz", include_in_schema=False)
    def healthz() -> dict:
        return {"ok": True, "mode": s.mode, "dialect": get_pool_singleton().dialect.value}

    @app.get("/v1/system/info", tags=["system"])
    def info() -> dict:
        """Unauthenticated, and deliberately says very little.

        Reports and the banner carry the hardware and date stamps, so a public
        deployment can state what it is without this endpoint leaking config.
        """
        return {
            "name": "ForgeSight",
            "mode": s.mode,
            "synthetic_demo_data": True,
            "notes": [
                "All evaluation data is generated by this repository and labelled SYNTHETIC.",
                "Benchmarks are valid only for the host and date recorded in the report.",
                "Absolute scores do not transfer to real documents; relative comparisons only.",
            ],
        }

    @app.exception_handler(ValueError)
    async def value_error_handler(request: Request, exc: ValueError) -> JSONResponse:
        return JSONResponse(status_code=400, content={"detail": str(exc)})

    return app


def _mount_web(app: FastAPI) -> None:
    """Serve the built frontend from the API, same origin (design §7).

    Only when a build exists. In development Vite serves the frontend and
    proxies /v1 here, so mounting is a no-op and the two cannot fight over a
    route. Serving from one origin in production removes the CORS question and
    the second base URL entirely.
    """
    dist = REPO_ROOT / "web" / "dist"
    if not (dist / "index.html").exists():
        return
    from fastapi.staticfiles import StaticFiles

    # Hashed asset filenames are immutable, so they can be cached hard; index.html
    # must not be, or a deploy would never reach a returning browser.
    app.mount(
        "/assets",
        StaticFiles(directory=dist / "assets"),
        name="assets",
    )

    @app.get("/", include_in_schema=False)
    @app.get("/{path:path}", include_in_schema=False)
    def spa(path: str = "") -> FileResponse:
        candidate = dist / path
        if path and candidate.is_file():
            return FileResponse(candidate)
        return FileResponse(dist / "index.html")

    log.info("serving the web build from %s", dist)


app = create_app()

__all__ = ["app", "create_app"]
